### PR TITLE
CORENET-5957:Rebase k8s to 1.33

### PR DESCRIPTION
**Pull request by meinali566**
go get -u github.com/openshift/build-machinery-go
go get -u k8s.io/api
go get -u k8s.io/apimachinery
go get -u k8s.io/code-generator
go get -u k8s.io/component-base
go get -u k8s.io/klog/v2
go get -u k8s.io/kube-proxy
go get -u k8s.io/utils
go get -u sigs.k8s.io/controller-runtime
go get -u github.com/openshift/api
go get -u github.com/openshift/client-go
go get -u github.com/openshift/library-go@release-4.20
go get -u github.com/openshift/machine-config-operator@release-4.20
go get -u k8s.io/apiextensions-apiserver
go get -u k8s.io/client-go
go get -u sigs.k8s.io/controller-tools
go mod tidy
go mod vendor

Here are a few additional fixes:
1. `k8s.io/apiserver@v0.33.3` still use `otelgrpc.UnaryClientInterceptor` which has been deprecated from otelgrpc since `v0.61.0`. so pin the version of `go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.60.0` (c.f. [ kubernetes/kubernetes#131942](https://github.com/kubernetes/kubernetes/issues/131942))
```
verndor/k8s.io/apiserver/pkg/storage/storagebackend/factory/etcd3.go:328:39: undefined: otelgrpc.UnaryClientInterceptor
```

2. there some conflict with kube-openapi and k8s.io/apimachinery ([kubernetes/apimachinery#190](https://github.com/kubernetes/apimachinery/issues/190)). There is a workaround that continue with kube-openapi's previous commit to the upgrade of sigs.k8s.io/structured-merge-diff: `go get k8s.io/kube-openapi@v0.0.0-20250701173324-9bd5c66d9911` (and k8s.io/X at v0.33.3)
```
# k8s.io/client-go/rest
../../go/pkg/mod/k8s.io/client-go@v0.33.2/rest/request.go:977:78: undefined: metav1.InitialEventsListBlueprintAnnotationKey
../../go/pkg/mod/k8s.io/client-go@v0.33.2/rest/request.go:979:89: undefined: metav1.InitialEventsListBlueprintAnnotationKey
```

### CODE REVIEW

**Comment by asood-rh** [comment]
@Meina-rh We would want to amend the commit message and also update the description of PR

**Comment by asood-rh** [comment]
@Meina-rh As this is rebase epic so versions come into play. The lint job is failing so you may have to get the version updated in https://github.com/openshift/release/blob/master/ci-operator/config/openshift/cluster-network-operator/openshift-cluster-network-operator-release-4.20.yaml#L9

For OVNK rebase v1.64.8 worked with 1.24.
name: Verify
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.64.8
        working-directory: go-controller
        args: --modules-download-mode=vendor --timeout=15m0s --verbose

cc @jcaamano @kyrtapz for opinion

**Comment by asood-rh** [comment]
@Meina-rh 
<pre>
there some conflict with kube-openapi and k8s.io/apimachinery (https://github.com/kubernetes/apimachinery/issues/190). There is a workaround that continue with kube-openapi's previous commit to the upgrade of sigs.k8s.io/structured-merge-diff: go get k8s.io/kube-openapi@v0.0.0-20250701173324-9bd5c66d9911 (and k8s.io/X at v0.33.3)
</pre>

Seems this workaround is applied in https://github.com/openshift/cloud-network-config-controller/pull/176 also.
Latest version of [kube-openapi](https://pkg.go.dev/k8s.io/kube-openapi@v0.0.0-20250710124328-f3f2b991d03b) is 20250710124328

Assuming we have to wait for issue to resolve for apimachinery to upgrade  kube-openapi to latest while other packages - k8s.io/apimachinery and  sigs.k8s.io/structured-merge-diff are latest.

**Comment by meinali566** [comment]
> @Meina-rh
> 
> there some conflict with kube-openapi and k8s.io/apimachinery (https://github.com/kubernetes/apimachinery/issues/190). There is a workaround that continue with kube-openapi's previous commit to the upgrade of sigs.k8s.io/structured-merge-diff: go get k8s.io/kube-openapi@v0.0.0-20250701173324-9bd5c66d9911 (and k8s.io/X at v0.33.3)
> Seems this workaround is applied in [openshift/cloud-network-config-controller#176](https://github.com/openshift/cloud-network-config-controller/pull/176) also. Latest version of [kube-openapi](https://pkg.go.dev/k8s.io/kube-openapi@v0.0.0-20250710124328-f3f2b991d03b) is 20250710124328
> 
> Assuming we have to wait for issue to resolve for apimachinery to upgrade kube-openapi to latest while other packages - k8s.io/apimachinery and sigs.k8s.io/structured-merge-diff are latest.

@asood-rh apimachinery has upgraded kube-openapi in v0.34.0-beta.0, but it's pre-release. It cannot be fixed in v0.33.x. so I think we better use this workaround.

**Comment by arkadeepsen** [comment]
Hey @Meina-rh, it would be great if you can break the PR into multiple commits (specially the vendored files) for ease of review. Following is my suggestion:
- All `go get` and `go mod tidy` in a single commit
- The `go mod vendor` in a single commit
- One commit each for each of the additional fixes (or maybe all of the additional fixes in a single commit)

**Comment by asood-rh** [comment]
> > @Meina-rh
> > there some conflict with kube-openapi and k8s.io/apimachinery ([kubernetes/apimachinery#190](https://github.com/kubernetes/apimachinery/issues/190)). There is a workaround that continue with kube-openapi's previous commit to the upgrade of sigs.k8s.io/structured-merge-diff: go get k8s.io/kube-openapi@v0.0.0-20250701173324-9bd5c66d9911 (and k8s.io/X at v0.33.3)
> > Seems this workaround is applied in [openshift/cloud-network-config-controller#176](https://github.com/openshift/cloud-network-config-controller/pull/176) also. Latest version of [kube-openapi](https://pkg.go.dev/k8s.io/kube-openapi@v0.0.0-20250710124328-f3f2b991d03b) is 20250710124328
> > Assuming we have to wait for issue to resolve for apimachinery to upgrade kube-openapi to latest while other packages - k8s.io/apimachinery and sigs.k8s.io/structured-merge-diff are latest.
> 
> @asood-rh apimachinery has upgraded kube-openapi in v0.34.0-beta.0, but it's pre-release. It cannot be fixed in v0.33.x. so I think we better use this workaround.

@Meina-rh We would want to use same method as Ricardo suggested in this PR as well.

**Comment by jluhrsen** [comment]
> Hey @Meina-rh, it would be great if you can break the PR into multiple commits (specially the vendored files) for ease of review. Following is my suggestion:
> 
> * All `go get` and `go mod tidy` in a single commit
> * The `go mod vendor` in a single commit
> * One commit each for each of the additional fixes (or maybe all of the additional fixes in a single commit)

I've tried it this way in the past as well, but I got a little push back about creating commits that would not actually build or pass tests. If the current group of approvers is ok with this, then I understand how it can make it easier to review.

what do you think @jcaamano ?

**Comment by meinali566** [comment]
hey @arkadeepsen , before your suggestion can be approved by the approvers, I’ve updated all my fixes using `replace` in `go.mod`. Hope this makes the review easier^^

File: go.mod [hunk 1]
```diff
@@ -136,37 +134,43 @@ require (
...
+	k8s.io/kms v0.33.3 // indirect
+	k8s.io/kube-aggregator v0.33.2 // indirect
 	sigs.k8s.io/randfill v1.0.0 // indirect
 )
+
+replace go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc => go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.60.0
+
+replace k8s.io/apimachinery => k8s.io/apimachinery v0.33.3
+
+replace k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20250701173324-9bd5c66d9911
```
Comment (arkadeepsen) [inline go.mod]:
```suggestion
replace (
	go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc => go.opentelemetry.io/contrib/instrumentation/google.golang.org/grpc/otelgrpc v0.60.0
	k8s.io/apimachinery => k8s.io/apimachinery v0.33.3
	k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20250701173324-9bd5c66d9911
)
```
nit: Instead of using multiple replace use a replace block.

File: go.mod [hunk 2]
```diff
@@ -61,69 +60,68 @@ require (
...
 )
 
 require (
-	github.com/openshift/api v0.0.0-20250530142525-6ff8c5bc1096
-	github.com/openshift/client-go v0.0.0-20250313171320-82b12a9e232b
-	github.com/openshift/library-go v0.0.0-20250313122028-477d5d90df06
+	github.com/openshift/api v0.0.0-20250723204313-9da003a73da3
+	github.com/openshift/client-go v0.0.0-20250710075018-396b36f983ee
+	github.com/openshift/library-go v0.0.0-20250711143941-47604345e7ea
 	github.com/openshift/machine-config-operator v0.0.1-0.20250301161121-24d9a767570d
```
Comment (arkadeepsen) [inline go.mod]: `github.com/openshift/machine-config-operator` is not upgraded. You can use the following to upgrade to the release-4.20 branch:

```shell
go get github.com/openshift/machine-config-operator@release4.20
```

File: go.mod [hunk 3]
```diff
@@ -61,69 +60,68 @@ require (
...
+	sigs.k8s.io/yaml v1.5.0 // indirect
 )
 
 require (
-	github.com/openshift/api v0.0.0-20250530142525-6ff8c5bc1096
-	github.com/openshift/client-go v0.0.0-20250313171320-82b12a9e232b
-	github.com/openshift/library-go v0.0.0-20250313122028-477d5d90df06
+	github.com/openshift/api v0.0.0-20250723204313-9da003a73da3
+	github.com/openshift/client-go v0.0.0-20250710075018-396b36f983ee
+	github.com/openshift/library-go v0.0.0-20250711143941-47604345e7ea
```
Comment (arkadeepsen) [inline go.mod]: `github.com/openshift/library-go` has a latest version. You can use the following to upgrade to the latest release-4.20 branch:
```shell
go get github.com/openshift/library-go@release-4.20
```

**Review by arkadeepsen — CHANGES_REQUESTED** [review]
Mostly looking good except for the below comments. Please make the following changes and update the commit message and PR description accordingly.

File: go.mod (hunk 2 above)
Comment (meinali566) [reply go.mod]: thanks. update code

File: go.mod (hunk 3 above)
Comment (meinali566) [reply go.mod]: update! thanks

File: go.mod (hunk 1 above)
Comment (meinali566) [reply go.mod]: thanks. update code

File: go.mod (hunk 2 above)
Comment (arkadeepsen) [reply go.mod]: This doesn't seem to have been updated.

File: go.mod [hunk 4]
```diff
@@ -136,37 +134,43 @@ require (
...
-	k8s.io/kms v0.32.3 // indirect
-	k8s.io/kube-aggregator v0.32.1 // indirect
+	k8s.io/apiserver v0.33.3 // indirect
+	k8s.io/gengo/v2 v2.0.0-20250704022524-ddb642e17a28 // indirect
+	k8s.io/kms v0.33.3 // indirect
+	k8s.io/kube-aggregator v0.33.2 // indirect
 	sigs.k8s.io/randfill v1.0.0 // indirect
 )
+
+replace (
```
Comment (arkadeepsen) [inline go.mod:173]: Can you also please add a comment above the replace block so that during the next package bump activity this replace block is removed.

File: go.mod (hunk 2 above)
Comment (meinali566) [reply go.mod]: oh correct, some packages don't download successfully. re-push them.

File: go.mod (hunk 4 above)
Comment (meinali566) [reply go.mod:173]: add^

**Review by arkadeepsen — APPROVED** [review]
/lgtm

**Comment by tssurya** [comment]
cc @pliurh for reviews and approve within this sprint....
@jcaamano will clear up approvers list.. but let's get this PR across the finishline

**Comment by tssurya** [comment]
we need this PR to merge for Peng to get rights https://github.com/openshift/cluster-network-operator/pull/2756
@kyrtapz meanwhile on behalf of peng can you slap the label here? - peng has approved this.

**Comment by pliurh** [comment]
/override pull-ci-openshift-cluster-network-operator-master-e2e-metal-ipi-ovn-dualstack-bgp-local-gw
